binary_sensor:
  - platform: template
    sensors:
      people_home:
        value_template: >-
          {{ is_state('device_tracker.andrej_oneplus6', 'home')
             or is_state('device_tracker.theresa_nokia6', 'home')
          }}