binary_sensor:
  - platform: template
    sensors:
      people_home:
        value_template: >-
          {{ is_state('person.andrej', 'home')
             or is_state('person.theresa', 'home')
          }}