automation:
- alias: 'Turn off bed heater after certain time'
  trigger:
    platform: state
    entity_id: switch.sonoff_basic_05_relay
    to: "on"
    for: '02:30:00'
  condition: []
  action:
  - service: switch.turn_off
    entity_id: switch.sonoff_basic_05_relay

- alias: 'Start timer for bedheater'
  trigger:
    platform: state
    entity_id: switch.sonoff_basic_05_relay
    from: "off"
    to: "on"
  condition: []
  action:
  - service: timer.start
    entity_id: timer.bed_heater

- alias: 'Stop bed heater after timer ended'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bed_heater
  condition: []
  action:
  - service: switch.turn_off
    entity_id: switch.sonoff_basic_05_relay

- alias: 'Reset timer when bed heater turns off'
  trigger:
    platform: state
    entity_id: switch.sonoff_basic_05_relay
    to: "off"
  condition: []
  action:
  - service: timer.cancel
    entity_id: timer.bed_heater

timer:
  bed_heater:
    name: "Timer Bettheizung"
    duration: '01:00:00'
    icon: mdi:timer

