- id: '1543790575213'
  alias: Upload Backup to Dropbox
  trigger:
  - entity_id: sensor.time
    platform: state
    to: '23:59'
  condition: []
  action:
  - data:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
    service: hassio.addon_stdin
  - data:
      message: Upload to dropbox started
      title: Upload Backup
    service: notify.chrome_push_oneplus6
- id: '1543791358275'
  alias: Benachrichtigung Waschmaschine fertig
  trigger:
  - below: '380'
    entity_id: sensor.sonoff_pow_03_power
    for: 00:05:00
    platform: numeric_state
  condition:
  - condition: state
    entity_id: switch.sonoff_pow_03_relay
    state: 'on'
  action:
  - data:
      message: Bin fertig
      title: Waschmaschine
    service: notify.chrome_push
  - data:
      entity_id: media_player.uberall
      message: Die Wäsche ist fertig!
    service: tts.google_say
- id: '1572183016472'
  alias: Neue Automatisierung
  description: ''
  trigger:
  - entity_id: sensor.0x00158d00023377e0_click
    platform: state
  condition: []
  action:
  - device_id: 98a383d5e6004187b73e40b78addda3f
    domain: light
    entity_id: light.stern
    type: toggle
