- id: '1543790575213'
  alias: Upload Backup to Dropbox
  trigger:
  - entity_id: sensor.time
    platform: state
    to: '23:59'
  condition: []
  action:
  - data:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
    service: hassio.addon_stdin
  - data:
      message: Upload to dropbox started
      title: Upload Backup
    service: notify.chrome_push_oneplus6
- id: '1543791358275'
  alias: Benachrichtigung Waschmaschine fertig
  trigger:
  - below: '30'
    entity_id: sensor.washing_machine_energy_power
    for: 00:03:00
    platform: numeric_state
  condition:
  - condition: state
    entity_id: switch.sonoff_pow_03_relay
    state: 'on'
  action:
  - data:
      message: Bin fertig
      title: Waschmaschine
    service: notify.chrome_push_oneplus6
  - data:
      message: Die Wäsche ist fertig!
    service: tts.google_say
- id: '1543791537354'
  alias: Andrej Zuhause verlassen
  trigger:
  - entity_id: device_tracker.andrej_oneplus6
    event: leave
    platform: zone
    zone: zone.home
  condition: []
  action:
  - data:
      message: Zuhause verlassen
      title: Andrej
    service: notify.chrome_push
- id: '1544994402306'
  alias: Make all Tasmota devices be automatically discovered
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      payload: '1'
      topic: cmnd/sonoffs/SetOption19
    service: mqtt.publish
  - data:
      payload: '1'
      topic: cmnd/sonoffs/SetOption55
    service: mqtt.publish
- id: '1544994472571'
  alias: Sync power state for MQTT devices
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      payload: ''
      topic: cmnd/sonoffs/state
    service: mqtt.publish
