- platform: google_travel_time
  api_key: !secret google_maps_key
  origin: device_tracker.andrej_oneplus5t
  destination: zone.his_work
  name: "Andrej to Work"
  options:
    mode: driving
    departure_time: now

- platform: google_travel_time
  api_key: !secret google_maps_key
  origin: device_tracker.andrej_oneplus5t
  destination: zone.home
  name: "Andrej to Home"
  options:
    mode: driving
    departure_time: now

- platform: google_travel_time
  api_key: !secret google_maps_key
  origin: device_tracker.theresa_motog3
  destination: zone.her_work
  name: "Theresa to Work"
  options:
    mode: bicycling
    departure_time: now

- platform: google_travel_time
  api_key: !secret google_maps_key
  origin: device_tracker.theresa_motog3
  destination: zone.home
  name: "Theresa to Home"
  options:
    mode: bicycling
    departure_time: now

- platform: cert_expiry
  host: ajfriesen.duckdns.org

- platform: haveibeenpwned
  email:
    - !secret mail_andrej1
    - !secret mail_theresa1
    - !secret mail_theresa2

- platform: time_date
  display_options:
    - 'time'

- platform: speedtest
  minute:
    - 0
    - 30
  monitored_conditions:
    - ping
    - download
    - upload

- platform: template
  sensors:
    someone_is_home:
      friendly_name: "Someone is home"
      value_template: '{% if "home" in [states.device_tracker.andrej_oneplus5t.state, states.device_tracker.theresa_motog3.state] %}yes{% else %}no{% endif %}'

- platform: mqtt
  name: "Washing Machine Wattage"
  state_topic: "tele/kitchen/washing-machine/ENERGY"
  value_template: "{{ value_json.Power }}"
  unit_of_measurement: "W"

- platform: mqtt
  name: "Washing Machine Voltage"
  state_topic: "tele/kitchen/washing-machine/ENERGY"
  value_template: "{{ value_json.Voltage }}"
  unit_of_measurement: "V"

- platform: mqtt
  name: "Washing Machine Current"
  state_topic: "tele/kitchen/washing-machine/ENERGY"
  value_template: "{{ value_json.Current }}"
  unit_of_measurement: "A"

- platform: template
  sensors:
    alarm_time_kitchen_socket:
      friendly_name: 'Kitchen Socket Start Time'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.alarmhour_kichten_socket") | int, states("input_number.alarmminutes_kitchen_socket") | int) }}'
      icon_template: >-
          {% if is_state('switch.kitchen_socket', 'on') %}
            mdi:timer
          {% else %}
            mdi:timer-off
          {% endif %}
