- platform: google_travel_time
  api_key: !secret google_maps_key
  origin: device_tracker.andrej_oneplus5t
  destination: !secret destination
  name: Work
  options:
    mode: driving
    departure_time: now

- platform: cert_expiry
  host: ajfriesen.duckdns.org

- platform: haveibeenpwned
  email:
    - !secret mail_andrej1
    - !secret mail_theresa1
    - !secret mail_theresa2

- platform: time_date
  display_options:
    - 'time'

- platform: speedtest
  minute:
    - 0
    - 30
  monitored_conditions:
    - ping
    - download
    - upload

