- platform: google_travel_time
  api_key: !secret google_maps_key
  origin: device_tracker.andrejs_phone
  destination: !secret destination
  name: Work
  options:
    mode: driving
    departure_time: now

- platform: cpuspeed

- platform: cert_expiry
  host: ajfriesen.duckdns.org

- platform: haveibeenpwned
  email:
    - !secret mail_andrej1
    - !secret mail_theresa1
    - !secret mail_theresa2

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'
    - 'beat'

# Weather prediction
- platform: yr
  name: Weather
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    - fog
    - cloudiness
    - lowClouds
    - mediumClouds
    - highClouds
    - dewpointTemperature

- platform: speedtest
  minute:
    - 0
    - 30
  monitored_conditions:
    - ping
    - download
    - upload

- platform: moon
