alias: Increment going out counter
hide_entity: true
initial_state: false
trigger:
  platform: time
  at: "08:00:00:00"
condition:
  - condition: time
    weekday:
      - sat
action:
  service: counter.increment
  entity_id: counter.going_out