alias: "Turn on Kitchen Socket"
hide_entity: true
initial_state: false
trigger:
  - platform: time_pattern
    minutes: '/1'
    seconds: 0
condition:
  - condition: state
    entity_id: input_boolean.kitchen_timer_active
    state: 'on'
  - condition: template
    value_template: '{{ now().strftime("%H:%M") == states.sensor.alarm_time_kitchen_socket.state }}'
action:
  - service: switch.turn_on
    entity_id: switch.sonoff_s20_02_relay
  - service: notify.chrome_push
    data:
      title: "Reiskocher"
      message: "Ich fang an zu kochen!"
  - service: input_boolean.turn_off
    entity_id: input_boolean.kitchen_timer_active
