alias: Morning Light
trigger:
  platform: time
  at: '06:20:00'
condition:
  condition: state
  entity_id: binary_sensor.workday_sensor
  state: 'on'
action:
  - service: light.turn_on
    data:
      brightness_pct: '1'
      entity_id:
        - light.bedroom
        - light.floor
  - service: light.turn_on
    data:
      entity_id:
        - light.light_string_bed
        - light.star
