alias: Tell that the vacuum is back at the dock again
hide_entity: true
initial_state: true
trigger:
  platform: state
  entity_id: vacuum.frodolin
  to: "docked"
action:
  service: notify.chrome_push
  data:
      title: "Frödolin"
      message: "Habe gesaugt Meister"
