alias: "Porch Animation Speed"
initial_state: True
hide_entity: False
trigger:
  - platform: state
    entity_id:
      - input_number.porch_animation_speed
action:
  - service: mqtt.publish
    data_template:
      topic: "bruh/porch/set"
      payload: '{"transition":{{ trigger.to_state.state | int }}}'
