# Turn on star 45 minutes before sunset
alias: Turn on star on sun dawn
trigger:
  platform: sun
  event: sunset
  offset: '-00:45:00'
condition:
  - condition: state
    entity_id: sensor.someone_is_home
    state: 'yes'
action:
  - service: script.evening_light