# Turn on star 45 minutes before sunset
alias: Turn on star on sun dawn
trigger:
  platform: sun
  event: sunset
  offset: '-00:45:00'
action:
- service: switch.turn_on
  entity_id:
    - switch.christmas_star
