alias: 'Turn off all lights when nobodys home'
trigger:
  platform: state
  entity_id: sensor.someone_is_home
  to: 'no'
action:
  - delay: '00:30:00'
  - service: light.turn_off
    entity_id: group.all_lights
