alias: Turn off Christmas Star
trigger:
  platform: state
  entity_id:
    - device_tracker.andrejs_phone
  from: 'home'
  to: 'not_home'
action:
- service: switch.turn_off
  entity_id:
    - switch.christmas_star
