alias: 'Start vacuum once a day when nobody is home'
trigger:
  - platform: state
    entity_id: sensor.someone_is_home
    from: 'yes'
    to: 'no'
    for:
      minutes: 5
condition:
    # At least one of the following is required.
  - condition: state
    entity_id: counter.vacuum_today
    state: '0'
  - condition: time
    after: '09:00:00'
    before: '21:00:00'
action:
  - service: vacuum.start
    data:
      entity_id: vacuum.frodolin
  - service: notify.chrome_push
    data:
      title: "Frödolin"
      message: "Ich fang an zu saugen!"