alias: "Wake me up with bedroom light transition for weekend days"
trigger:
  - platform: time
    minutes: '/1'
    seconds: 0
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.alarm_active_weekend
      state: 'on'
    - condition: state
      entity_id: input_boolean.alarm_active_weekday
      state: 'off'
    - condition: time
      weekday:
        - sat
        - sun
    - condition: template
      value_template: '{{ now().strftime("%H:%M") == states.sensor.alarm_time.state }}'
action:
  service: script.morning_light