alias: "Wake me up with bedroom light transition for weekdays"
trigger:
  - platform: time
    minutes: '/1'
    seconds: 0
condition:
  - condition: state
    entity_id: input_boolean.alarm_active_weekday
    state: 'on'
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: template
    value_template: '{{ now().strftime("%H:%M") == states.sensor.alarm_time.state }}'
action:
  service: script.morning_light