esphome:
  name: epaper
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret epaper_static_ip
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Example configuration entry
spi:
  clk_pin: D0
  mosi_pin: D1

font:
  - file: "COMIC.ttf"
    id: font
    size: 20

display:
  - platform: waveshare_epaper
    cs_pin: D2
    dc_pin: D3
    busy_pin: D4
    reset_pin: D5
    model: 2.90in
    full_update_every: 30
    lambda: |-
      it.print(0, 0, id(font), "Hello World!");