esphome:
  name: sonoff_s20_02
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    manual_ip:
      static_ip: !secret sonoff_s20_02_static_ip
      gateway: !secret wifi_gateway
      subnet: !secret wifi_subnet
  reboot_timeout: 0s
  ap:
    ssid: ${devicename}
    password: !secret esphome_ap_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      then:
        - switch.toggle: relay
    name: "sonoff_s20_02_button"
  - platform: status
    name: "sonoff_s20_02_status"


switch:
  - platform: gpio
    name: "sonoff_s20_02_relay"
    pin: GPIO12
    id: relay
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led

output:
  # Register the green LED as a dimmable output ....
  - platform: esp8266_pwm
    id: s20_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "sonoff_s20_02_led"
    output: s20_green_led
    id: led