esphome:
  name: sonoff_pow_03
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
  # - ssid: !secret wifi_ssid
  #   password: !secret wifi_password
  #   manual_ip:
  #     static_ip: !secret sonoff_pow_03_static_ip
  #     gateway: !secret wifi_gateway
  #     subnet: !secret wifi_subnet
  - ssid: !secret wifi_ssid_2
    password: !secret wifi_password_2
    manual_ip:
      static_ip: !secret sonoff_pow_03_static_ip
      gateway: !secret wifi_gateway_2
      subnet: !secret wifi_subnet
  reboot_timeout: 0s

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      then:
        - switch.toggle: relay
    name: "sonoff_pow_03_button"
  - platform: status
    name: "sonoff_pow_03_status"

sensor:
  - platform: hlw8012
    sel_pin: 5
    cf_pin: 14
    cf1_pin: 13
    current:
      name: "sonoff_pow_03_current"
    voltage:
      name: "sonoff_pow_03_voltage"
    power:
      name: "sonoff_pow_03_power"
    update_interval: 30s

switch:
  - platform: gpio
    name: "sonoff_pow_03_relay"
    pin: GPIO12
    id: relay
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led

output:
  # Register the green LED as a dimmable output ....
  - platform: esp8266_pwm
    id: pow_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "sonoff_pow_03_green_led"
    output: pow_green_led
    id: led