---
# Device: sonoff basic
# Light chain in the cube
#

substitutions:
  devicename: sonoff_basic_07
  upper_devicename: Würfel

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    manual_ip:
      static_ip: !secret sonoff_basic_07_static_ip
      gateway: !secret wifi_gateway
      subnet: !secret wifi_subnet
  reboot_timeout: 0s
  ap:
    ssid: ${devicename}
    password: !secret esphome_ap_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: wifi_signal
    name: ${devicename}_wifi_signal
    update_interval: 10s
  - platform: uptime
    name: ${devicename}_uptime

text_sensor:
  - platform: version
    name: ${devicename}_esphome_version

# GPIO13 Green LED
status_led:
  pin:
    number: GPIO13
    inverted: yes

# GPIO0 Button inverted
binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${devicename}_button
    on_press:
      - light.toggle: lamp

# GPIO12 Relay
output:
  - platform: gpio
    id: relay
    pin: GPIO12  

light:
  - platform: binary
    id: lamp
    name: ${upper_devicename}
    output: relay