---
# Device: sonoff basic
# Switch for powercord
# Used as ligth switch for a standing lamp

substitutions:
  devicename: sonoff_basic_01
  upper_devicename: Stehlampe

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
  # - ssid: !secret wifi_ssid
  #   password: !secret wifi_password
  #   manual_ip:
  #     static_ip: !secret sonoff_basic_01_static_ip
  #     gateway: !secret wifi_gateway
  #     subnet: !secret wifi_subnet
  - ssid: !secret wifi_ssid_2
    password: !secret wifi_password_2
    manual_ip:
      static_ip: !secret sonoff_basic_01_static_ip
      gateway: !secret wifi_gateway_2
      subnet: !secret wifi_subnet
  reboot_timeout: 0s

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:

sensor:
  - platform: wifi_signal
    name: ${devicename}_wifi_signal
    update_interval: 10s
  - platform: uptime
    name: ${devicename}_uptime

text_sensor:
  - platform: version
    name: ${devicename}_esphome_version

# GPIO13 Green LED
status_led:
  pin:
    number: GPIO13
    inverted: yes

# GPIO0 Button inverted
binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${devicename}_button
    on_press:
      - light.toggle: lamp

# GPIO12 Relay
output:
  - platform: gpio
    id: relay
    pin: GPIO12  

light:
  - platform: binary
    id: lamp
    name: ${upper_devicename}
    output: relay