###   Command line to install gmusicapi
shell_command:
  install_gmusic: pip3 install gmusicapi==10.1.2

input_text:
  playlist:
    name: playlist
    initial: BootValue

input_select:
  music:
    name: Music
    options:
     - " "   # Should be empty
    icon: mdi:music-note
  media_player:
    name: Media player
    options: # entity_ids of your media players
     - "uberall"
     - "allles_ausser_schlafzimme"
     - "googlehome5980"
     - "googlehome7873"
     - "googlehome8941"
     - "wohnzimmer"
    icon: mdi:music-note

switch:
 - platform: gmusic
   user: !secret gmusic_user
   password: !secret gpassword
   device_id: !secret gmusic_device_id # http://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.login
   media_player: media_player # entity id of the input select used for mediaplayer
   playlist: music # entity id of the input select used for playlist

script:
  musicoff:
    alias: Turn off the Music
    sequence:
    - service: media_player.turn_off
      entity_id: media_player.uberall
    - service: switch.turn_off
      entity_id: switch.google_music

  musicon:
    alias: Turn on the Google Music Switch
    sequence:
    - service: switch.turn_on
      entity_id: switch.google_music

  playlist:
    alias: Playlist Script from RFID
    sequence:
    - service: script.musicoff
    - service: input_select.select_option
      data_template:
        entity_id: input_select.music
        option: '{{ states.input_text.playlist.state }}'
    - service: input_select.select_option
      data:
        entity_id: input_select.media_player
        option: "uberall"
    - service: script.volume30
    - service: script.musicon
    - service: input_text.set_value
      data_template:
        entity_id: input_text.playlist
        value: "BootValue"

  volume30:
      alias: Set Volume of Media to 30%
      sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.uberall
          volume_level: 0.3

  volume40:
      alias: Set Volume of Media to 40%
      sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.uberall
          volume_level: 0.4

automation:
- action:
  - service: script.playlist
  alias: Playlist Value Changes
  condition:
  - condition: template
    value_template: '{{ states.input_text.playlist.state != "BootValue" }}'
  id: '1521492851100'
  trigger:
  - entity_id: input_text.playlist
    from: BootValue
    platform: state